# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"load": "00_core.ipynb",
         "save": "00_core.ipynb",
         "DATA_DIR": "00_core.ipynb",
         "to_int": "00_core.ipynb",
         "flatten": "02_norvig.ipynb",
         "md5": "00_core.ipynb",
         "arr_to_dict": "00_core.ipynb",
         "reverse_dict": "00_core.ipynb",
         "untar_data": "00_core.ipynb",
         "timeit": "00_core.ipynb",
         "nan_inspect": "00_core.ipynb",
         "neighbors": "00_core.ipynb",
         "arr_neighbors": "00_core.ipynb",
         "dimensions": "00_core.ipynb",
         "Dim": "00_core.ipynb",
         "positive": "00_core.ipynb",
         "manhattan": "00_core.ipynb",
         "conv1d": "00_core.ipynb",
         "conv2d": "00_core.ipynb",
         "binarysearch": "00_core.ipynb",
         "deduce_matches": "00_core.ipynb",
         "bfs": "00_core.ipynb",
         "dijkstra": "00_core.ipynb",
         "get_path": "00_core.ipynb",
         "dfs": "00_core.ipynb",
         "find_pattern_in_iter": "00_core.ipynb",
         "find_repeat": "00_core.ipynb",
         "find_cycle": "00_core.ipynb",
         "factors": "00_core.ipynb",
         "CFG": "01_context_free_grammar.ipynb",
         "cfg": "01_context_free_grammar.ipynb",
         "data": "02_norvig.ipynb",
         "do": "02_norvig.ipynb",
         "quantify": "02_norvig.ipynb",
         "first": "02_norvig.ipynb",
         "rest": "02_norvig.ipynb",
         "multimap": "02_norvig.ipynb",
         "prod": "02_norvig.ipynb",
         "ints": "02_norvig.ipynb",
         "test": "02_norvig.ipynb",
         "atom": "02_norvig.ipynb",
         "atoms": "02_norvig.ipynb",
         "list_atoms": "02_norvig.ipynb",
         "dotproduct": "02_norvig.ipynb",
         "mapt": "02_norvig.ipynb",
         "cat": "02_norvig.ipynb",
         "Char": "02_norvig.ipynb",
         "zippify": "02_norvig.ipynb"}

modules = ["aoc.py",
           "aoccfg.py",
           "aocnorvig.py"]

doc_url = "https://jvanelteren.github.io/aocutils/"

git_url = "https://github.com/jvanelteren/aocutils/tree/main/"

def custom_doc_links(name): return None
