# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Test": "00_core.ipynb"}

modules = ["aoc_second.py",
           "aoc.py"]

doc_url = "https://jvanelteren.github.io/utils/"

git_url = "https://github.com/jvanelteren/utils/tree/branch/"

def custom_doc_links(name): return None
